### ISSUE TITLE
Identifier with the wrong timestamp

### ISSUE THREAD

**Issue by pedromancheno** [whitesmith/ulid#3]
```
import ULID
print(ULID().ulidString)
```
Running this results in an identifier with a timestamp in the year 1970. I realised this happens because the precision is in seconds and not milliseconds. Thus, I am currently using the other initializer for ULID.

```
ULID(timestamp: Date().timeIntervalSince1970, generator: { return UInt.random() })
```

**Comment by ricardopereira** [comment]
Fixed with 2b167d4bc5f5afdbb4865a8432d190857d0ea3b9.
